env_name: 'BipedalWalker-v3'
n_steps: 1024
mini_batch_size: 64
max_train_steps: 4000000
lr_a: 0.004
lr_c: 0.001
gamma: 0.99
lamda: 0.95
epsilon: 0.2
K_epochs: 7
entropy_coef: 0.01
num_envs: 16
normalize_state: True
normalize_reward: True
is_continuous: True
clip_decay: False
lr_decay: False
ini_method: 7 
seed: 42
n_blocks: 1
n_wires: 4
which_classical: 0
# use_quafu: True
# key: 