env_name: 'LunarLander-v3'
n_steps: 1024
mini_batch_size: 64
max_train_steps: 1750000
lr_a: 0.003
lr_c: 0.0003
gamma: 0.999
lamda: 0.98
epsilon: 0.2
K_epochs: 4
entropy_coef: 0.01
num_envs: 16
normalize_state: False
normalize_reward: False
is_continuous: True
clip_decay: False
lr_decay: False
ini_method: 4  
seed: 42
n_blocks: 1
n_wires: 4
which_classical: 0
# use_quafu: True
# key: 