env_name: 'MountainCar-v0'
n_steps: 16
mini_batch_size: 64
max_train_steps: 1000000
lr_a: 0.003
lr_c: 0.0003
gamma: 0.99
lamda: 0.98
epsilon: 0.2
K_epochs: 4
entropy_coef: 0.00
num_envs: 16
normalize_state: True
normalize_reward: True
is_continuous: False
clip_decay: False
lr_decay: False
ini_method: 0 
seed: 42
n_blocks: 3
n_wires: 2
which_classical: 0
# use_quafu: True
# key: 
