env_name: 'Pendulum-v1'
n_steps: 1024
mini_batch_size: 64
max_train_steps: 100000
lr_a: 0.01
lr_c: 0.001
gamma: 0.9
lamda: 0.95
epsilon: 0.2
K_epochs: 10
entropy_coef: 0.00
num_envs: 4
normalize_state: False
normalize_reward: False
is_continuous: True
clip_decay: False
lr_decay: False
ini_method: 2 
seed: 42
n_blocks: 2
n_wires: 3
which_classical: 0
# use_quafu: True
# key: 

